
services:
  #http://corpgateway.localtest.me/web/home?0
  #primaryHostID: corporate 
  corpGateway:
    image: inductiveautomation/ignition:${IGN_VERSION:-8.1.49}
    container_name: ${CORP_IGN_GATEWAY_NAME}
    hostname: ${CORP_IGN_GATEWAY_NAME}
    user: 0:0
    volumes:
      # Gateway backup
      - ./gw-init/corpGateway.gwbk:/restore.gwbk
      # Ignition data
      - ignDataCorp:/usr/local/bin/ignition/data
      #Ignition module seeds
      - ./module-init/MQTT-Engine-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Engine.modl
    labels:
      - traefik.enable=true
      - traefik.hostname=${CORP_IGN_GATEWAY_NAME}
    environment:
      ACCEPT_IGNITION_EULA: 'Y'
      GATEWAY_ADMIN_USERNAME: ${CORP_IGN_USERNAME}
      GATEWAY_ADMIN_PASSWORD: ${CORP_IGN_PASSWORD}
      IGNITION_EDITION: ${CORP_IGN_EDITION}
      TZ: ${IGN_TZ:-America/New_York}
      DISABLE_QUICKSTART: 'true'
    # ports:
    #   - ${CORP_IGN_GATEWAY_PORT}:8088
    command: >
      -n ${CORP_IGN_GATEWAY_NAME}
      -h 80
      -s 443
      -a ${CORP_IGN_GATEWAY_NAME}
      -r /restore.gwbk      
    networks:
      - default
    profiles: ["corpGateway"]
      
  siteGateway:
    image: inductiveautomation/ignition:${IGN_VERSION}
    container_name: ${SITE_IGN_GATEWAY_NAME}
    hostname: ${SITE_IGN_GATEWAY_NAME}
    user: 0:0
    volumes:
      # Gateway backup
      - ./gw-init/siteGateway.gwbk:/restore.gwbk
      # Ignition data
      - ignDataSite:/usr/local/bin/ignition/data
      #Ignition module seeds
      - ./module-init/MQTT-Engine-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Engine.modl
      - ./module-init/MQTT-Distributor-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Distributor-signed.modl
      - ./module-init/MQTT-Transmission-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Transmission-signed.modl
    labels:
      - traefik.enable=true
      - traefik.hostname=${SITE_IGN_GATEWAY_NAME}
    environment:
      ACCEPT_IGNITION_EULA: 'Y'
      GATEWAY_ADMIN_USERNAME: ${SITE_IGN_USERNAME}
      GATEWAY_ADMIN_PASSWORD: ${SITE_IGN_PASSWORD}
      IGNITION_EDITION: ${SITE_IGN_EDITION}
      TZ: ${IGN_TZ:-America/New_York}
      DISABLE_QUICKSTART: 'true'
    # ports:
      # - "1883:1883"  
    #   - ${SITE_IGN_GATEWAY_PORT}:8088    
    command: >
      -n ${SITE_IGN_GATEWAY_NAME}
      -h 80
      -s 443
      -a ${SITE_IGN_GATEWAY_NAME}
      -r /restore.gwbk
    networks:
      - default
    profiles: ["siteGateway"]
       
  siteEdgeGateway1:
    image: inductiveautomation/ignition:${IGN_VERSION}
    container_name: ${EDGE_IGN_GATEWAY_NAME}
    hostname: ${EDGE_IGN_GATEWAY_NAME}
    user: 0:0
    volumes:
      # Gateway backup
      - ./gw-init/siteEdgeGateway.gwbk:/restore.gwbk
      # Ignition data
      - ignDataEdge:/usr/local/bin/ignition/data
      #Ignition module seeds
      - ./module-init/MQTT-Transmission-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Transmission.modl
    labels:
      - traefik.enable=true
      - traefik.hostname=${EDGE_IGN_GATEWAY_NAME}
    environment:
      ACCEPT_IGNITION_EULA: 'Y'
      GATEWAY_ADMIN_USERNAME: ${EDGE_IGN_USERNAME}
      GATEWAY_ADMIN_PASSWORD: ${EDGE_IGN_PASSWORD}
      IGNITION_EDITION: ${EDGE_IGN_EDITION:-edge}
      TZ: ${IGN_TZ:-America/New_York}
      DISABLE_QUICKSTART: 'true'
    # ports:
    #   - ${EDGE_IGN_GATEWAY_PORT}:8088  
    command: >
      -n ${EDGE_IGN_GATEWAY_NAME}
      -h 80
      -s 443
      -a ${EDGE_IGN_GATEWAY_NAME}
      -r /restore.gwbk
    networks:
      - default
    profiles: ["siteEdgeGateway1"]

  edgeGateway1:
    image: inductiveautomation/ignition:${IGN_VERSION}
    container_name: ${EDGE_IGN1_GATEWAY_NAME}
    hostname: ${EDGE_IGN1_GATEWAY_NAME}
    user: 0:0
    volumes:
      # Gateway backup
      - ./gw-init/edgeGateway1.gwbk:/restore.gwbk
      # Ignition data
      - ignDataEdge1:/usr/local/bin/ignition/data
      #Ignition module seeds
      - ./module-init/MQTT-Transmission-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Transmission.modl
    labels:
      - traefik.enable=true
      - traefik.hostname=${EDGE_IGN1_GATEWAY_NAME}
    environment:
      ACCEPT_IGNITION_EULA: 'Y'
      GATEWAY_ADMIN_USERNAME: ${EDGE_IGN1_USERNAME}
      GATEWAY_ADMIN_PASSWORD: ${EDGE_IGN1_PASSWORD}
      IGNITION_EDITION: ${EDGE_IGN1_EDITION}
      TZ: ${IGN_TZ:-America/New_York}
      DISABLE_QUICKSTART: 'true'
    # ports:
    #   - ${EDGE_IGN1_GATEWAY_PORT}:8088  
    command: >
      -n ${EDGE_IGN1_GATEWAY_NAME}
      -h 80
      -s 443
      -a ${EDGE_IGN1_GATEWAY_NAME}
      -r /restore.gwbk
    networks:
      - default
    profiles: ["edgeGateway1"]

  edgeGateway2:
    image: inductiveautomation/ignition:${IGN_VERSION}
    container_name: ${EDGE_IGN2_GATEWAY_NAME}
    hostname: ${EDGE_IGN2_GATEWAY_NAME}
    user: 0:0
    volumes:
      # Gateway backup
      - ./gw-init/edgeGateway2.gwbk:/restore.gwbk
      # Ignition data
      - ignDataEdge2:/usr/local/bin/ignition/data
      #Ignition module seeds
      - ./module-init/MQTT-Transmission-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Transmission.modl
    labels:
      - traefik.enable=true
      - traefik.hostname=${EDGE_IGN2_GATEWAY_NAME}
    environment:
      ACCEPT_IGNITION_EULA: 'Y'
      GATEWAY_ADMIN_USERNAME: ${EDGE_IGN2_USERNAME}
      GATEWAY_ADMIN_PASSWORD: ${EDGE_IGN2_PASSWORD}
      IGNITION_EDITION: ${EDGE_IGN_EDITION}
      TZ: ${IGN_TZ:-America/New_York}
      DISABLE_QUICKSTART: 'true'
    # ports:
    #   - ${EDGE_IGN2_GATEWAY_PORT}:8088  
    command: >
      -n ${EDGE_IGN2_GATEWAY_NAME}
      -h 80
      -s 443
      -a ${EDGE_IGN2_GATEWAY_NAME}
      -r /restore.gwbk
    networks:
      - default
    profiles: ["edgeGateway2"]

  #-----------------------------------------------------------------------------------------------------------------------------  
  #Postgres Ignition Connection Settings
      #Name: Postgres
      #Username: ignition
      #Password: ignition

    #Gateway running in dockerstack:
      #Connect URL: jdbc:postgresql://corpPostgres/corpPostgres  
  corpPostgres:
    image: postgres
    hostname: ${CORP_POSTG_DB:-corpGWNPostgres}
    container_name: ${CORP_POSTG_DB:-corpGWNPostgres}
    volumes:
      - postgDataCorp:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${CORP_POSTG_DB:-corpGWNPostgres}
      POSTGRES_USER: ${CORP_POSTG_USER:-ignition}
      POSTGRES_PASSWORD: ${CORP_POSTG_PASSWORD:-ignition}
      TZ: ${IGN_TZ:-America/New_York}
    networks:
      - default
    profiles: ["corpPostgres"]


  #Postgres Ignition Connection Settings
      #Name: PostgresSite
      #Username: ignition
      #Password: ignition

    #Gateway running in dockerstack:
      #Connect URL: jdbc:postgresql://sitePostgres/sitePostgres  
  sitePostgres:
    image: postgres
    hostname: ${SITE_POSTG_DB:-siteGWNPostgres}
    container_name: ${SITE_POSTG_DB:-siteGWNPostgres}
    volumes:
      - postgDataSite:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SITE_POSTG_DB:-siteGWNPostgres}
      POSTGRES_USER: ${SITE_POSTG_USER:-ignition}
      POSTGRES_PASSWORD: ${SITE_POSTG_PASSWORD:-ignition}
      TZ: ${IGN_TZ:-America/New_York}
    networks:
      - default
    profiles: ["sitePostgres"]
#---------------------------------------------------------------------------------
  chariot:
    build:
      context: . # The build context is the current directory
      dockerfile: dockerfile # Specifies the name of the dockerfile
    container_name: chariot-server
    restart: unless-stopped
    ports:
      - "1883:1883" # MQTT Port
      - "8080:8080" # Web UI Port
    volumes:
      # This maps a local folder to the container's data directory
      # for persistent configuration and data.
      - ./chariot-data:/usr/local/chariot/data
    networks:
      - default
    profiles: ["chariot"]
#---------------------------------------------------------------------------------
#EQMX Initial username and Password
      #Username: admin 
      #Password: public ► Ignition1!
      #Dashboard: http://localhost:18083/#/dashboard/overview

  emqx:
    image: emqx/emqx:latest
    hostname: emqx
    container_name: emqx
    ports:
#      - "1883:1883"        # MQTT
#      - "8883:8883"        # MQTT/TLS
      - "8083:8083"        # HTTP Management
      - "18083:18083"      # Dashboard
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
      - EMQX_NODE__DIST_LISTEN_MAX=6379
    volumes:
      - emqx:/opt/emqx/data
      - emqxlog:/opt/emqx/log
    networks:
      - default
    profiles: ["emqx"]


networks:
  default:
    external: true
    name: proxy
    driver: bridge

volumes:
    ignDataCorp:
    ignDataSite:
    ignDataEdge:
    ignDataEdge1:
    ignDataEdge2:
    postgDataCorp:
    postgDataSite:
    emqx:
    emqxlog:
